version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456aA@
      POSTGRES_DB: test-ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  my-quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-micro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/test-ecommerce
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: 123456aA@

volumes:
  postgres_data:
